# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backend_proto/item_messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!backend_proto/item_messages.proto\x12\x10sims_ims_backend\"P\n\x08ItemInfo\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x11\n\tobject_id\x18\x02 \x01(\r\x12\r\n\x05price\x18\x03 \x01(\r\x12\r\n\x05stock\x18\x04 \x01(\r\"u\n\x11\x43reateItemRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08shelf_id\x18\x02 \x01(\t\x12\x13\n\x0bslot_number\x18\x03 \x01(\r\x12(\n\x04info\x18\x04 \x01(\x0b\x32\x1a.sims_ims_backend.ItemInfo\"\x14\n\x12\x43reateItemResponse\"3\n\x0fReadItemRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07item_id\x18\x02 \x01(\t\"<\n\x10ReadItemResponse\x12(\n\x04info\x18\x01 \x01(\x0b\x32\x1a.sims_ims_backend.ItemInfo\"c\n\x11UpdateItemRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07item_id\x18\x02 \x01(\t\x12,\n\x08new_info\x18\x03 \x01(\x0b\x32\x1a.sims_ims_backend.ItemInfo\"\x14\n\x12UpdateItemResponse\"5\n\x11\x44\x65leteItemRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07item_id\x18\x02 \x01(\t\"\x14\n\x12\x44\x65leteItemResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backend_proto.item_messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ITEMINFO._serialized_start=55
  _ITEMINFO._serialized_end=135
  _CREATEITEMREQUEST._serialized_start=137
  _CREATEITEMREQUEST._serialized_end=254
  _CREATEITEMRESPONSE._serialized_start=256
  _CREATEITEMRESPONSE._serialized_end=276
  _READITEMREQUEST._serialized_start=278
  _READITEMREQUEST._serialized_end=329
  _READITEMRESPONSE._serialized_start=331
  _READITEMRESPONSE._serialized_end=391
  _UPDATEITEMREQUEST._serialized_start=393
  _UPDATEITEMREQUEST._serialized_end=492
  _UPDATEITEMRESPONSE._serialized_start=494
  _UPDATEITEMRESPONSE._serialized_end=514
  _DELETEITEMREQUEST._serialized_start=516
  _DELETEITEMREQUEST._serialized_end=569
  _DELETEITEMRESPONSE._serialized_start=571
  _DELETEITEMRESPONSE._serialized_end=591
# @@protoc_insertion_point(module_scope)
