# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backend_proto/slot_messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!backend_proto/slot_messages.proto\x12\x10sims_ims_backend\"B\n\x08SlotInfo\x12\x10\n\x08slot_num\x18\x01 \x01(\r\x12\x10\n\x08\x63\x61pacity\x18\x02 \x01(\r\x12\x12\n\nitem_count\x18\x03 \x01(\r\"N\n\x11\x43reateSlotRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12(\n\x04info\x18\x02 \x01(\x0b\x32\x1a.sims_ims_backend.SlotInfo\"\x14\n\x12\x43reateSlotResponse\"F\n\x0fReadSlotRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08shelf_id\x18\x02 \x01(\t\x12\x10\n\x08slot_num\x18\x03 \x01(\r\"<\n\x10ReadSlotResponse\x12(\n\x04info\x18\x01 \x01(\x0b\x32\x1a.sims_ims_backend.SlotInfo\"v\n\x11UpdateSlotRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08shelf_id\x18\x02 \x01(\t\x12\x10\n\x08slot_num\x18\x03 \x01(\r\x12,\n\x08new_info\x18\x04 \x01(\x0b\x32\x1a.sims_ims_backend.SlotInfo\"\x14\n\x12UpdateSlotResponse\"H\n\x11\x44\x65leteSlotRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08shelf_id\x18\x02 \x01(\t\x12\x10\n\x08slot_num\x18\x03 \x01(\r\"\x14\n\x12\x44\x65leteSlotResponse\"\xd3\x01\n\x12\x43reateSlotsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08shelf_id\x18\x02 \x01(\t\x12\r\n\x05slots\x18\x03 \x01(\r\x12\r\n\x03\x61ll\x18\x04 \x01(\rH\x00\x12\x44\n\x04\x65\x61\x63h\x18\x05 \x01(\x0b\x32\x34.sims_ims_backend.CreateSlotsRequest.PerSlotCapacityH\x00\x1a#\n\x0fPerSlotCapacity\x12\x10\n\x08\x63\x61pacity\x18\x01 \x03(\rB\x11\n\x0fslot_capacities\"\x15\n\x13\x43reateSlotsResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backend_proto.slot_messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SLOTINFO._serialized_start=55
  _SLOTINFO._serialized_end=121
  _CREATESLOTREQUEST._serialized_start=123
  _CREATESLOTREQUEST._serialized_end=201
  _CREATESLOTRESPONSE._serialized_start=203
  _CREATESLOTRESPONSE._serialized_end=223
  _READSLOTREQUEST._serialized_start=225
  _READSLOTREQUEST._serialized_end=295
  _READSLOTRESPONSE._serialized_start=297
  _READSLOTRESPONSE._serialized_end=357
  _UPDATESLOTREQUEST._serialized_start=359
  _UPDATESLOTREQUEST._serialized_end=477
  _UPDATESLOTRESPONSE._serialized_start=479
  _UPDATESLOTRESPONSE._serialized_end=499
  _DELETESLOTREQUEST._serialized_start=501
  _DELETESLOTREQUEST._serialized_end=573
  _DELETESLOTRESPONSE._serialized_start=575
  _DELETESLOTRESPONSE._serialized_end=595
  _CREATESLOTSREQUEST._serialized_start=598
  _CREATESLOTSREQUEST._serialized_end=809
  _CREATESLOTSREQUEST_PERSLOTCAPACITY._serialized_start=755
  _CREATESLOTSREQUEST_PERSLOTCAPACITY._serialized_end=790
  _CREATESLOTSRESPONSE._serialized_start=811
  _CREATESLOTSRESPONSE._serialized_end=832
# @@protoc_insertion_point(module_scope)
