# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backend_proto/user_messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!backend_proto/user_messages.proto\x12\x10sims_ims_backend\"\x1b\n\x08UserInfo\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"=\n\x11\x43reateUserRequest\x12(\n\x04info\x18\x01 \x01(\x0b\x32\x1a.sims_ims_backend.UserInfo\"\x14\n\x12\x43reateUserResponse\";\n\x0fReadUserRequest\x12(\n\x04info\x18\x01 \x01(\x0b\x32\x1a.sims_ims_backend.UserInfo\"<\n\x10ReadUserResponse\x12(\n\x04info\x18\x01 \x01(\x0b\x32\x1a.sims_ims_backend.UserInfo\"=\n\x11\x44\x65leteUserRequest\x12(\n\x04info\x18\x01 \x01(\x0b\x32\x1a.sims_ims_backend.UserInfo\"\x14\n\x12\x44\x65leteUserResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backend_proto.user_messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERINFO._serialized_start=55
  _USERINFO._serialized_end=82
  _CREATEUSERREQUEST._serialized_start=84
  _CREATEUSERREQUEST._serialized_end=145
  _CREATEUSERRESPONSE._serialized_start=147
  _CREATEUSERRESPONSE._serialized_end=167
  _READUSERREQUEST._serialized_start=169
  _READUSERREQUEST._serialized_end=228
  _READUSERRESPONSE._serialized_start=230
  _READUSERRESPONSE._serialized_end=290
  _DELETEUSERREQUEST._serialized_start=292
  _DELETEUSERREQUEST._serialized_end=353
  _DELETEUSERRESPONSE._serialized_start=355
  _DELETEUSERRESPONSE._serialized_end=375
# @@protoc_insertion_point(module_scope)
