# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iis.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import user_messages_pb2 as user__messages__pb2
import shelf_messages_pb2 as shelf__messages__pb2
import slot_messages_pb2 as slot__messages__pb2
import item_messages_pb2 as item__messages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tiis.proto\x12\x07SimsIMS\x1a\x13user_messages.proto\x1a\x14shelf_messages.proto\x1a\x13slot_messages.proto\x1a\x13item_messages.proto2\xa7\t\n\x1eSimsInventoryInformationSystem\x12G\n\nCreateUser\x12\x1a.SimsIMS.CreateUserRequest\x1a\x1b.SimsIMS.CreateUserResponse\"\x00\x12\x41\n\x08ReadUser\x12\x18.SimsIMS.ReadUserRequest\x1a\x19.SimsIMS.ReadUserResponse\"\x00\x12G\n\nDeleteUser\x12\x1a.SimsIMS.DeleteUserRequest\x1a\x1b.SimsIMS.DeleteUserResponse\"\x00\x12J\n\x0b\x43reateShelf\x12\x1b.SimsIMS.CreateShelfRequest\x1a\x1c.SimsIMS.CreateShelfResponse\"\x00\x12\x44\n\tReadShelf\x12\x19.SimsIMS.ReadShelfRequest\x1a\x1a.SimsIMS.ReadShelfResponse\"\x00\x12J\n\x0bUpdateShelf\x12\x1b.SimsIMS.UpdateShelfRequest\x1a\x1c.SimsIMS.UpdateShelfResponse\"\x00\x12J\n\x0b\x44\x65leteShelf\x12\x1b.SimsIMS.DeleteShelfRequest\x1a\x1c.SimsIMS.DeleteShelfResponse\"\x00\x12G\n\nCreateSlot\x12\x1a.SimsIMS.CreateSlotRequest\x1a\x1b.SimsIMS.CreateSlotResponse\"\x00\x12\x41\n\x08ReadSlot\x12\x18.SimsIMS.ReadSlotRequest\x1a\x19.SimsIMS.ReadSlotResponse\"\x00\x12G\n\nUpdateSlot\x12\x1a.SimsIMS.UpdateSlotRequest\x1a\x1b.SimsIMS.UpdateSlotResponse\"\x00\x12G\n\nDeleteSlot\x12\x1a.SimsIMS.DeleteSlotRequest\x1a\x1b.SimsIMS.DeleteSlotResponse\"\x00\x12J\n\x0b\x43reateSlots\x12\x1b.SimsIMS.CreateSlotsRequest\x1a\x1c.SimsIMS.CreateSlotsResponse\"\x00\x12G\n\nCreateItem\x12\x1a.SimsIMS.CreateItemRequest\x1a\x1b.SimsIMS.CreateItemResponse\"\x00\x12\x41\n\x08ReadItem\x12\x18.SimsIMS.ReadItemRequest\x1a\x19.SimsIMS.ReadItemResponse\"\x00\x12G\n\nUpdateItem\x12\x1a.SimsIMS.UpdateItemRequest\x1a\x1b.SimsIMS.UpdateItemResponse\"\x00\x12G\n\nDeleteItem\x12\x1a.SimsIMS.DeleteItemRequest\x1a\x1b.SimsIMS.DeleteItemResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'iis_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIMSINVENTORYINFORMATIONSYSTEM._serialized_start=108
  _SIMSINVENTORYINFORMATIONSYSTEM._serialized_end=1299
# @@protoc_insertion_point(module_scope)
