# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iis.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import user_messages_pb2 as user__messages__pb2
import shelf_messages_pb2 as shelf__messages__pb2
import slot_messages_pb2 as slot__messages__pb2
import item_messages_pb2 as item__messages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tiis.proto\x12\x10sims_ims_backend\x1a\x13user_messages.proto\x1a\x14shelf_messages.proto\x1a\x13slot_messages.proto\x1a\x13item_messages.proto2\xc7\x0b\n\x1eSimsInventoryInformationSystem\x12Y\n\nCreateUser\x12#.sims_ims_backend.CreateUserRequest\x1a$.sims_ims_backend.CreateUserResponse\"\x00\x12S\n\x08ReadUser\x12!.sims_ims_backend.ReadUserRequest\x1a\".sims_ims_backend.ReadUserResponse\"\x00\x12Y\n\nDeleteUser\x12#.sims_ims_backend.DeleteUserRequest\x1a$.sims_ims_backend.DeleteUserResponse\"\x00\x12\\\n\x0b\x43reateShelf\x12$.sims_ims_backend.CreateShelfRequest\x1a%.sims_ims_backend.CreateShelfResponse\"\x00\x12V\n\tReadShelf\x12\".sims_ims_backend.ReadShelfRequest\x1a#.sims_ims_backend.ReadShelfResponse\"\x00\x12\\\n\x0bUpdateShelf\x12$.sims_ims_backend.UpdateShelfRequest\x1a%.sims_ims_backend.UpdateShelfResponse\"\x00\x12\\\n\x0b\x44\x65leteShelf\x12$.sims_ims_backend.DeleteShelfRequest\x1a%.sims_ims_backend.DeleteShelfResponse\"\x00\x12Y\n\nCreateSlot\x12#.sims_ims_backend.CreateSlotRequest\x1a$.sims_ims_backend.CreateSlotResponse\"\x00\x12S\n\x08ReadSlot\x12!.sims_ims_backend.ReadSlotRequest\x1a\".sims_ims_backend.ReadSlotResponse\"\x00\x12Y\n\nUpdateSlot\x12#.sims_ims_backend.UpdateSlotRequest\x1a$.sims_ims_backend.UpdateSlotResponse\"\x00\x12Y\n\nDeleteSlot\x12#.sims_ims_backend.DeleteSlotRequest\x1a$.sims_ims_backend.DeleteSlotResponse\"\x00\x12\\\n\x0b\x43reateSlots\x12$.sims_ims_backend.CreateSlotsRequest\x1a%.sims_ims_backend.CreateSlotsResponse\"\x00\x12Y\n\nCreateItem\x12#.sims_ims_backend.CreateItemRequest\x1a$.sims_ims_backend.CreateItemResponse\"\x00\x12S\n\x08ReadItem\x12!.sims_ims_backend.ReadItemRequest\x1a\".sims_ims_backend.ReadItemResponse\"\x00\x12Y\n\nUpdateItem\x12#.sims_ims_backend.UpdateItemRequest\x1a$.sims_ims_backend.UpdateItemResponse\"\x00\x12Y\n\nDeleteItem\x12#.sims_ims_backend.DeleteItemRequest\x1a$.sims_ims_backend.DeleteItemResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'iis_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIMSINVENTORYINFORMATIONSYSTEM._serialized_start=117
  _SIMSINVENTORYINFORMATIONSYSTEM._serialized_end=1596
# @@protoc_insertion_point(module_scope)
